# Generated by Django 3.2.7 on 2021-09-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Question', max_length=255, verbose_name='Title'),
        ),
    ]
