# Generated by Django 3.2.7 on 2021-09-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='date_updated',
        ),
    ]
